//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AdminMessage
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage ="This Field is required")]
        public string Message_desc { get; set; }
        public string TimeStemp { get; set; }
        public int User_Id { get; set; }
    
        public virtual User User { get; set; }
    }
}
