//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Id { get; set; }
        public string Details { get; set; }
        public int User_Id { get; set; }
        public int Item_Id { get; set; }
    
        public virtual User User { get; set; }
        public virtual Item Item { get; set; }
    }
}
