//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Carts = new HashSet<Cart>();
            this.Reviews = new HashSet<Review>();
            this.Order_Details = new HashSet<Order_Details>();
        }
    
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "This Field is required")]
        [Display(Name="Item Number")]
        public string Number { get; set; }
        [Required(ErrorMessage = "This Field is required")]
        [Display(Name = "Item Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "This Field is required")]
        public string Size { get; set; }
        [Required(ErrorMessage = "This Field is required")]
        public string Color { get; set; }
        [Required(ErrorMessage = "This Field is required")]
        public string Unit { get; set; }
        [Required(ErrorMessage = "This Field is required")]
        public double Price { get; set; }
        [Required(ErrorMessage = "This Field is required")]
        public string Discount { get; set; }
        public int Brand_Name { get; set; }
        [Required(ErrorMessage = "This Field is required")]
        public byte[] Image { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<int> SubCategory_Id { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual Subcategory Subcategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Details> Order_Details { get; set; }
    }
}
